[project]
name = "2026-02-json-curation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
    "numpy>=2.4.2",
    "openai>=2.17.0",
    "seaborn>=0.13.2",
]
